CREATE DATABASE IF NOT EXISTS TALLER_2 ;
USE TALLER_2;

DROP TABLE IF EXISTS ITEM_PEDIDO;
DROP TABLE IF EXISTS PEDIDO;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS PRODUCTO;

CREATE TABLE PRODUCTO(
	ID_PRODUCTO INT PRIMARY KEY auto_increment,
    NOMBRE varchar(50) NOT NULL,
    DESCRIPCION varchar(50) NOT NULL,
    CLASIFICACION varchar(50) NOT NULL,
    IMAGEN	VARCHAR(100) NULL,
    PRECIO double NOT NULL
);

CREATE TABLE PEDIDO(
	ID_PEDIDO INT PRIMARY KEY auto_increment,
	ID_TOKEN VARCHAR(500) NULL,
    FECHA date
);
CREATE TABLE ITEM_PEDIDO(
	ID_ITEM INT PRIMARY KEY auto_increment,
	ID_PEDIDO INT,
    CANTIDAD INT,
    ID_PRODUCTO INT,
    CONSTRAINT FK_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
    CONSTRAINT FK_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);