CREATE DATABASE IF NOT EXISTS TALLER_2 ;
USE TALLER_2;

DROP TABLE IF EXISTS ITEM_PEDIDO;
DROP TABLE IF EXISTS PEDIDO;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS PRODUCTO;

CREATE TABLE USUARIO(
	ID_USUARIO INT PRIMARY KEY auto_increment,
    EMAIL varchar(50) NOT NULL,
    CONTRASENA varchar(50) NOT NULL,
    NOMBRE varchar(50) NOT NULL,
    APELLIDO varchar(50) NOT NULL,
	DIRECCION VARCHAR(50) NOT NULL,
    ROLusuario VARCHAR(50) NULL
);

CREATE TABLE PRODUCTO(
	ID_PRODUCTO INT PRIMARY KEY auto_increment,
    NOMBRE varchar(50) NOT NULL,
    DESCRIPCION varchar(50) NOT NULL,
    CLASIFICACION varchar(50) NOT NULL,
    IMAGEN	VARCHAR(100) NULL,
    PRECIO double NOT NULL
);

CREATE TABLE PEDIDO(
	ID_PEDIDO INT PRIMARY KEY auto_increment,
	ID_USUARIO INT,
    FECHA date,
    CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);
CREATE TABLE ITEM_PEDIDO(
	ID_ITEM INT PRIMARY KEY auto_increment,
	ID_PEDIDO INT,
    ID_PRODUCTO INT,
    CONSTRAINT FK_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
    CONSTRAINT FK_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);